import {
  permissionIds,
  roleIds,
  type PermissionId,
  type RoleId,
  type UserProfile,
} from "@/types/domain";

const permissionsByRole: Readonly<Record<RoleId, readonly PermissionId[]>> = {
  system_administrator: permissionIds,
  operations_administrator: [
    "user.manage",
    "report.read",
    "request.approve",
    "transfer.create",
    "transfer.approve",
    "products.read",
    "inventory.read",
    "inventory.reconcile",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.review",
    "requests.request_changes",
    "requests.approve",
    "requests.reject",
    "requests.cancel_approved",
    "requests.close",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.create.from_request",
    "transfers.create.direct",
    "transfers.update_draft",
    "transfers.submit",
    "transfers.review",
    "transfers.approve",
    "transfers.cancel",
    "transfers.reserve",
    "transfers.release_reservation",
    "transfers.resolve_discrepancy",
    "transfers.close",
    "reports.transfers.read",
    "reports.transfers.export",
    "sales.read.all",
    "sales.create",
    "sales.shift.manage",
    "sales.price.branch.manage",
    "customers.read",
    "customers.manage",
    "customers.payment.record",
    "sales.credit.create",
    "sales.returns.read",
    "sales.returns.create",
    "sales.returns.approve",
    "reports.sales.read",
    "suppliers.read",
    "suppliers.manage",
    "procurement.read",
    "procurement.create",
    "procurement.approve",
    "expenses.read",
    "expenses.create",
    "expenses.approve",
  ],
  warehouse_manager: [
    "report.read",
    "request.approve",
    "transfer.approve",
    "inventory.operate",
    "logistics.manage",
    "products.read",
    "products.create",
    "products.update",
    "inventory.read",
    "inventory.receive",
    "inventory.opening_stock",
    "inventory.move_internal",
    "inventory.adjust",
    "inventory.reverse",
    "inventory.count",
    "inventory.count_review",
    "inventory.reconcile",
    "inventory.cost.read",
    "inventory.cost.manage",
    "reports.inventory.read",
    "reports.inventory.export",
    "suppliers.read",
    "procurement.read",
    "procurement.create",
    "procurement.receive",
    "expenses.read",
    "expenses.create",
    "requests.read.all",
    "requests.review",
    "requests.request_changes",
    "requests.approve",
    "requests.reject",
    "requests.cancel_approved",
    "requests.close",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.assigned_warehouse",
    "transfers.create.from_request",
    "transfers.update_draft",
    "transfers.submit",
    "transfers.review",
    "transfers.approve",
    "transfers.cancel",
    "transfers.reserve",
    "transfers.release_reservation",
    "transfers.pick",
    "transfers.check_pick",
    "transfers.pack",
    "transfers.check_pack",
    "transfers.dispatch",
    "transfers.verify_dispatch",
    "transfers.report_discrepancy",
    "transfers.resolve_discrepancy",
    "transfers.cost.read",
    "transfers.cost.create",
    "transfers.cost.approve",
    "transfers.cost.reconcile",
    "transfers.close",
    "reports.transfers.read",
    "reports.transfers.export",
    "sales.price.base.manage",
  ],
  warehouse_officer: [
    "inventory.operate",
    "products.read",
    "inventory.read",
    "inventory.count",
    "requests.read.all",
    "transfers.read.assigned_warehouse",
    "transfers.pick",
    "transfers.pack",
    "transfers.report_discrepancy",
    "suppliers.read",
    "procurement.read",
    "procurement.receive",
  ],
  branch_requester: [
    "request.create",
    "requests.read.own_branch",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.cancel_own",
    "transfers.read.own_branch",
    "transfers.report_discrepancy",
  ],
  branch_manager: [
    "request.create",
    "receipt.confirm",
    "products.read",
    "inventory.read",
    "inventory.receive",
    "inventory.opening_stock",
    "inventory.move_internal",
    "inventory.adjust",
    "inventory.reverse",
    "inventory.count",
    "inventory.count_review",
    "inventory.reconcile",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.own_branch",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.cancel_own",
    "requests.cancel_approved",
    "requests.close",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.own_branch",
    "transfers.receive",
    "transfers.report_discrepancy",
    "reports.transfers.read",
    "reports.transfers.export",
    "sales.read.own_branch",
    "sales.create",
    "sales.shift.manage",
    "sales.price.branch.manage",
    "customers.read",
    "customers.manage",
    "customers.payment.record",
    "sales.credit.create",
    "sales.returns.read",
    "sales.returns.create",
    "sales.returns.approve",
    "reports.sales.read",
    "expenses.read",
    "expenses.create",
  ],
  sales_cashier: [
    "products.read",
    "inventory.read",
    "sales.read.own_branch",
    "sales.create",
    "sales.shift.manage",
    "sales.credit.create",
    "sales.returns.read",
    "sales.returns.create",
  ],
  logistics_officer: [
    "logistics.manage",
    "cost.create",
    "transfers.read.all",
    "transfers.pack",
    "transfers.dispatch",
    "transfers.cost.create",
    "transfers.report_discrepancy",
    "reports.transfers.read",
  ],
  finance_officer: [
    "report.read",
    "cost.create",
    "cost.approve",
    "products.read",
    "inventory.read",
    "inventory.cost.read",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.cost.read",
    "transfers.cost.create",
    "transfers.cost.approve",
    "transfers.cost.reconcile",
    "reports.transfers.read",
    "reports.transfers.export",
    "sales.read.all",
    "customers.read",
    "customers.payment.record",
    "sales.returns.read",
    "sales.returns.approve",
    "reports.sales.read",
    "finance.journal.read",
    "suppliers.read",
    "procurement.read",
    "payables.read",
    "payables.create",
    "payables.approve",
    "payables.pay",
    "expenses.read",
    "expenses.create",
    "expenses.approve",
    "expenses.pay",
    "banking.read",
    "banking.manage",
    "banking.reconcile",
    "banking.approve",
  ],
  auditor: [
    "audit.read",
    "report.read",
    "report.export",
    "products.read",
    "inventory.read",
    "inventory.cost.read",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.cost.read",
    "reports.transfers.read",
    "reports.transfers.export",
    "sales.read.all",
    "customers.read",
    "sales.returns.read",
    "reports.sales.read",
    "finance.journal.read",
    "suppliers.read",
    "procurement.read",
    "payables.read",
    "expenses.read",
    "banking.read",
  ],
};

export function permissionsForRoles(
  roleIds: readonly RoleId[],
): ReadonlySet<PermissionId> {
  return new Set(roleIds.flatMap((roleId) => permissionsByRole[roleId]));
}

export function hasPermission(
  profile: Pick<UserProfile, "status" | "roleId" | "roleIds">,
  permission: PermissionId,
): boolean {
  if (profile.status !== "active") return false;
  const assignedRoles = roleIdsForProfile(profile);
  if (assignedRoles.includes("system_administrator")) return true;
  return permissionsForRoles(assignedRoles).has(permission);
}

export function hasAnyPermission(
  profile: Pick<UserProfile, "status" | "roleId" | "roleIds">,
  permissions: readonly PermissionId[],
): boolean {
  return permissions.some((permission) => hasPermission(profile, permission));
}

export function roleIdsForProfile(
  profile: Pick<UserProfile, "roleId" | "roleIds">,
): readonly RoleId[] {
  const selected = new Set(
    profile.roleIds?.length ? profile.roleIds : [profile.roleId],
  );
  return roleIds.filter((roleId) => selected.has(roleId));
}

export function hasRole(
  profile: Pick<UserProfile, "roleId" | "roleIds">,
  roleId: RoleId,
): boolean {
  return roleIdsForProfile(profile).includes(roleId);
}

export function isAssignedToBranch(
  profile: Pick<UserProfile, "branchIds">,
  branchId: string,
): boolean {
  return profile.branchIds.includes(branchId);
}
