import { roleIds, type PermissionId, type RoleId, type UserProfile } from "@/types/domain";

const permissionsByRole: Readonly<Record<RoleId, readonly PermissionId[]>> = {
  system_administrator: [
    "organization.manage",
    "branch.manage",
    "warehouse.manage",
    "location.manage",
    "user.manage",
    "role.manage",
    "audit.read",
    "products.read",
    "products.create",
    "products.update",
    "inventory.read",
    "inventory.receive",
    "inventory.opening_stock",
    "inventory.move_internal",
    "inventory.adjust",
    "inventory.reverse",
    "inventory.count",
    "inventory.count_review",
    "inventory.reconcile",
    "inventory.cost.read",
    "inventory.cost.manage",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.cancel_own",
    "requests.review",
    "requests.request_changes",
    "requests.approve",
    "requests.reject",
    "requests.cancel_approved",
    "requests.close",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.create.from_request",
    "transfers.create.direct",
    "transfers.update_draft",
    "transfers.submit",
    "transfers.review",
    "transfers.approve",
    "transfers.cancel",
    "transfers.reserve",
    "transfers.release_reservation",
    "transfers.pick",
    "transfers.check_pick",
    "transfers.pack",
    "transfers.check_pack",
    "transfers.dispatch",
    "transfers.verify_dispatch",
    "transfers.receive",
    "transfers.report_discrepancy",
    "transfers.resolve_discrepancy",
    "transfers.cost.read",
    "transfers.cost.create",
    "transfers.cost.approve",
    "transfers.cost.reconcile",
    "transfers.close",
    "reports.transfers.read",
    "reports.transfers.export",
  ],
  operations_administrator: [
    "user.manage",
    "report.read",
    "request.approve",
    "transfer.create",
    "transfer.approve",
    "products.read",
    "inventory.read",
    "inventory.reconcile",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.review",
    "requests.request_changes",
    "requests.approve",
    "requests.reject",
    "requests.cancel_approved",
    "requests.close",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.create.from_request",
    "transfers.create.direct",
    "transfers.update_draft",
    "transfers.submit",
    "transfers.review",
    "transfers.approve",
    "transfers.cancel",
    "transfers.reserve",
    "transfers.release_reservation",
    "transfers.resolve_discrepancy",
    "transfers.close",
    "reports.transfers.read",
    "reports.transfers.export",
  ],
  warehouse_manager: [
    "report.read",
    "request.approve",
    "transfer.approve",
    "inventory.operate",
    "logistics.manage",
    "products.read",
    "products.create",
    "products.update",
    "inventory.read",
    "inventory.receive",
    "inventory.move_internal",
    "inventory.adjust",
    "inventory.reverse",
    "inventory.count",
    "inventory.count_review",
    "inventory.cost.read",
    "inventory.cost.manage",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.review",
    "requests.request_changes",
    "requests.approve",
    "requests.reject",
    "requests.cancel_approved",
    "requests.close",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.assigned_warehouse",
    "transfers.create.from_request",
    "transfers.update_draft",
    "transfers.submit",
    "transfers.review",
    "transfers.approve",
    "transfers.cancel",
    "transfers.reserve",
    "transfers.release_reservation",
    "transfers.pick",
    "transfers.check_pick",
    "transfers.pack",
    "transfers.check_pack",
    "transfers.dispatch",
    "transfers.verify_dispatch",
    "transfers.report_discrepancy",
    "transfers.resolve_discrepancy",
    "transfers.cost.read",
    "transfers.cost.create",
    "transfers.close",
    "reports.transfers.read",
    "reports.transfers.export",
  ],
  warehouse_officer: [
    "inventory.operate",
    "products.read",
    "inventory.read",
    "inventory.count",
    "requests.read.all",
    "transfers.read.assigned_warehouse",
    "transfers.pick",
    "transfers.pack",
    "transfers.report_discrepancy",
  ],
  branch_requester: [
    "request.create",
    "requests.read.own_branch",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.cancel_own",
    "transfers.read.own_branch",
    "transfers.report_discrepancy",
  ],
  branch_manager: [
    "request.create",
    "receipt.confirm",
    "products.read",
    "inventory.read",
    "requests.read.own_branch",
    "requests.create",
    "requests.update_draft",
    "requests.submit",
    "requests.cancel_own",
    "reports.requests.read",
    "transfers.read.own_branch",
    "transfers.receive",
    "transfers.report_discrepancy",
    "reports.transfers.read",
  ],
  logistics_officer: [
    "logistics.manage",
    "cost.create",
    "transfers.read.all",
    "transfers.pack",
    "transfers.dispatch",
    "transfers.cost.create",
    "transfers.report_discrepancy",
    "reports.transfers.read",
  ],
  finance_officer: [
    "report.read",
    "cost.create",
    "cost.approve",
    "products.read",
    "inventory.read",
    "inventory.cost.read",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.cost.read",
    "transfers.cost.create",
    "transfers.cost.approve",
    "transfers.cost.reconcile",
    "reports.transfers.read",
    "reports.transfers.export",
  ],
  auditor: [
    "audit.read",
    "report.read",
    "report.export",
    "products.read",
    "inventory.read",
    "inventory.cost.read",
    "reports.inventory.read",
    "reports.inventory.export",
    "requests.read.all",
    "requests.cost.read",
    "reports.requests.read",
    "reports.requests.export",
    "transfers.read.all",
    "transfers.cost.read",
    "reports.transfers.read",
    "reports.transfers.export",
  ],
};

export function permissionsForRoles(
  roleIds: readonly RoleId[],
): ReadonlySet<PermissionId> {
  return new Set(roleIds.flatMap((roleId) => permissionsByRole[roleId]));
}

export function hasPermission(
  profile: Pick<UserProfile, "status" | "roleId" | "roleIds">,
  permission: PermissionId,
): boolean {
  if (profile.status !== "active") return false;
  return permissionsForRoles(roleIdsForProfile(profile)).has(permission);
}

export function roleIdsForProfile(
  profile: Pick<UserProfile, "roleId" | "roleIds">,
): readonly RoleId[] {
  const selected = new Set(
    profile.roleIds?.length ? profile.roleIds : [profile.roleId],
  );
  return roleIds.filter((roleId) => selected.has(roleId));
}

export function hasRole(
  profile: Pick<UserProfile, "roleId" | "roleIds">,
  roleId: RoleId,
): boolean {
  return roleIdsForProfile(profile).includes(roleId);
}

export function isAssignedToBranch(
  profile: Pick<UserProfile, "branchIds">,
  branchId: string,
): boolean {
  return profile.branchIds.includes(branchId);
}
