import { deleteApp, initializeApp, type FirebaseApp } from "firebase/app";
import { connectAuthEmulator, getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { connectFunctionsEmulator, getFunctions, httpsCallable } from "firebase/functions";
import { getApps as getAdminApps, initializeApp as initializeAdminApp } from "firebase-admin/app";
import { getAuth as getAdminAuth } from "firebase-admin/auth";
import { FieldValue, getFirestore } from "firebase-admin/firestore";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { balanceDocumentId, uniquenessDocumentId } from "../functions/src/inventory/calculations";

const projectId = "demo-ramadan-warehouse", organizationId = "lot-transfer-org";
const adminApp = getAdminApps().find((app) => app.name === "lot-transfer-e2e") ?? initializeAdminApp({ projectId }, "lot-transfer-e2e");
const adminAuth = getAdminAuth(adminApp), adminDb = getFirestore(adminApp), apps: FirebaseApp[] = [];
function client(name: string) { const app = initializeApp({ projectId, apiKey: "demo", appId: `lot-${name}` }, `lot-${name}`); apps.push(app); const auth = getAuth(app); connectAuthEmulator(auth, "http://127.0.0.1:9099", { disableWarnings: true }); const functions = getFunctions(app, "us-central1"); connectFunctionsEmulator(functions, "127.0.0.1", 5001); return { auth, functions }; }
async function call<T>(target: ReturnType<typeof client>, name: string, data: Record<string, unknown>) { return (await httpsCallable(target.functions, name)(data)).data as T; }
async function actor(name: string, roleId: string, branchIds: string[] = [], warehouseIds: string[] = []) { const email = `lot-${name}@example.test`; const user = await adminAuth.createUser({ email, password: "Password!234567" }); await adminDb.doc(`users/${user.uid}`).set({ uid: user.uid, organizationId, email, displayName: name, roleId, branchIds, warehouseIds, status: "active", authDisabled: false, authorizationVersion: 1 }); const result = client(name); await signInWithEmailAndPassword(result.auth, email, "Password!234567"); return { ...result, uid: user.uid }; }
let creator: Awaited<ReturnType<typeof actor>>, manager: Awaited<ReturnType<typeof actor>>, picker: Awaited<ReturnType<typeof actor>>, logistics: Awaited<ReturnType<typeof actor>>, receiver: Awaited<ReturnType<typeof actor>>;
const lotA = uniquenessDocumentId(organizationId, "lot-product", "CABLE-A"), lotB = uniquenessDocumentId(organizationId, "lot-product", "CABLE-B");
beforeAll(async () => {
  await fetch(`http://127.0.0.1:9099/emulator/v1/projects/${projectId}/accounts`, { method: "DELETE" }); await fetch(`http://127.0.0.1:8180/emulator/v1/projects/${projectId}/databases/(default)/documents`, { method: "DELETE" });
  await Promise.all([
    adminDb.doc(`organizations/${organizationId}`).set({ name: "Lot Test", openingStockEnabled: true, createdAt: FieldValue.serverTimestamp() }),
    adminDb.doc("warehouses/lot-wh").set({ organizationId, name: "Central", code: "CEN", status: "active" }), adminDb.doc("branches/lot-branch").set({ organizationId, name: "Abuja", code: "ABJ", status: "active" }),
    adminDb.doc("inventoryLocations/lot-origin").set({ organizationId, warehouseId: "lot-wh", name: "Available", code: "AVL", type: "warehouse", status: "active" }), adminDb.doc("inventoryLocations/lot-destination").set({ organizationId, branchId: "lot-branch", name: "Branch", code: "BRA", type: "branch", status: "active" }),
    adminDb.doc("products/lot-product").set({ organizationId, name: "6mm² DC Solar Cable", sku: "CAB-6MM", unitOfMeasure: "roll", trackingType: "batch", active: true, hasLedgerActivity: false }), adminDb.doc("productCosts/lot-product").set({ organizationId, productId: "lot-product", defaultUnitCostMinor: 10_000, currency: "NGN" }),
  ]);
  creator = await actor("creator", "system_administrator"); manager = await actor("manager", "warehouse_manager", [], ["lot-wh"]); picker = await actor("picker", "warehouse_officer", [], ["lot-wh"]); logistics = await actor("logistics", "logistics_officer", [], ["lot-wh"]); receiver = await actor("receiver", "branch_manager", ["lot-branch"]);
  await call(creator, "postOpeningStock", { productId: "lot-product", destinationLocationId: "lot-origin", quantity: 5, unitCostMinor: 10_000, lot: { lotNumber: "CABLE-A" }, effectiveAt: new Date().toISOString(), reason: "Lot A opening balance", externalAccount: "migration", idempotencyKey: crypto.randomUUID() });
  await call(creator, "postOpeningStock", { productId: "lot-product", destinationLocationId: "lot-origin", quantity: 5, unitCostMinor: 20_000, lot: { lotNumber: "CABLE-B" }, effectiveAt: new Date().toISOString(), reason: "Lot B opening balance", externalAccount: "migration", idempotencyKey: crypto.randomUUID() });
}, 60_000);
afterAll(async () => Promise.all(apps.map((app) => deleteApp(app))));

describe.sequential("lot transfer callable E2E", () => {
  it("preserves exact multi-lot quantities and costs across partial and final receipt", async () => {
    const created = await call<{ transferId: string }>(creator, "createAdminTransfer", { originWarehouseId: "lot-wh", originLocationId: "lot-origin", destinationBranchId: "lot-branch", destinationLocationId: "lot-destination", purpose: "Cable replenishment by controlled lots", priority: "normal", items: [{ productId: "lot-product", quantity: 6 }], directTransferReason: "Branch cable replenishment", idempotencyKey: crypto.randomUUID() });
    const transferId = created.transferId, transferItemId = `${transferId}__lot-product`, allocations = [{ lotId: lotA, quantity: 4 }, { lotId: lotB, quantity: 2 }];
    await call(creator, "submitTransfer", { transferId, expectedVersion: 0, idempotencyKey: crypto.randomUUID() }); await call(manager, "approveTransfer", { transferId, expectedVersion: 1, idempotencyKey: crypto.randomUUID() });
    await expect(call(manager, "reserveTransferStock", { transferId, expectedVersion: 1, lines: [{ transferItemId, productId: "lot-product", quantity: 11, lotAllocations: [{ lotId: lotA, quantity: 6 }, { lotId: lotB, quantity: 5 }], serialItemIds: [] }], idempotencyKey: crypto.randomUUID() })).rejects.toMatchObject({ code: "functions/failed-precondition" });
    await expect(call(manager, "reserveTransferStock", { transferId, expectedVersion: 1, lines: [{ transferItemId, productId: "lot-product", quantity: 6, lotAllocations: [{ lotId: lotA, quantity: 4 }, { lotId: lotB, quantity: 1 }], serialItemIds: [] }], idempotencyKey: crypto.randomUUID() })).rejects.toMatchObject({ code: "functions/invalid-argument" });
    await call(manager, "reserveTransferStock", { transferId, expectedVersion: 1, lines: [{ transferItemId, productId: "lot-product", quantity: 6, lotAllocations: allocations, serialItemIds: [] }], idempotencyKey: crypto.randomUUID() });
    expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", "lot-origin", lotA)}`).get()).get("reservedQuantity")).toBe(4); expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", "lot-origin", lotB)}`).get()).get("reservedQuantity")).toBe(2);
    await call(picker, "startTransferPicking", { transferId, expectedVersion: 1, idempotencyKey: crypto.randomUUID() }); const pick = await call<{ pickId: string }>(picker, "recordPickedItems", { transferId, expectedVersion: 1, lines: [{ transferItemId, quantity: 6, lotAllocations: allocations, serialItemIds: [] }], idempotencyKey: crypto.randomUUID() }); await call(manager, "verifyPickedItems", { transferId, expectedVersion: 1, pickId: pick.pickId, accepted: true, idempotencyKey: crypto.randomUUID() });
    const pkg = await call<{ packageId: string }>(picker, "createTransferPackage", { transferId, expectedVersion: 1, lines: [{ transferItemId, quantity: 6, lotAllocations: allocations, serialItemIds: [] }], idempotencyKey: crypto.randomUUID() }); await call(picker, "sealTransferPackage", { transferId, expectedVersion: 1, packageId: pkg.packageId, idempotencyKey: crypto.randomUUID() }); await call(manager, "verifyPacking", { transferId, expectedVersion: 1, packageId: pkg.packageId, idempotencyKey: crypto.randomUUID() });
    const dispatchBase = { transferId, expectedVersion: 1, packageIds: [pkg.packageId], driverName: "Aisha Musa", verifiedBy: manager.uid }; const dispatch = await call<{ dispatchId: string }>(logistics, "createTransferDispatch", { ...dispatchBase, idempotencyKey: crypto.randomUUID() }); await call(logistics, "confirmTransferDispatch", { ...dispatchBase, dispatchId: dispatch.dispatchId, idempotencyKey: crypto.randomUUID() });
    async function receive(quantity: number, receiptAllocations: Array<{ lotId: string; quantity: number; disposition: "received" }>) { const base = { transferId, expectedVersion: 1, dispatchId: dispatch.dispatchId, deliveryCondition: "good", lines: [{ transferItemId, receivedQuantity: quantity, damagedQuantity: 0, missingQuantity: 0, rejectedQuantity: 0, serialItemIds: [], damagedSerialItemIds: [], lotAllocations: receiptAllocations }] }; const receipt = await call<{ receiptId: string }>(receiver, "createTransferReceipt", { ...base, idempotencyKey: crypto.randomUUID() }); await call(receiver, "confirmTransferReceipt", { ...base, receiptId: receipt.receiptId, idempotencyKey: crypto.randomUUID() }); }
    await receive(4, [{ lotId: lotA, quantity: 3, disposition: "received" }, { lotId: lotB, quantity: 1, disposition: "received" }]); await receive(2, [{ lotId: lotA, quantity: 1, disposition: "received" }, { lotId: lotB, quantity: 1, disposition: "received" }]);
    expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", "lot-destination", lotA)}`).get()).data()).toMatchObject({ onHandQuantity: 4, averageUnitCostMinor: 10_000 }); expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", "lot-destination", lotB)}`).get()).data()).toMatchObject({ onHandQuantity: 2, averageUnitCostMinor: 20_000 });
    expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", `transit__${organizationId}__lot-branch`, lotA)}`).get()).get("onHandQuantity")).toBe(0); expect((await adminDb.doc(`inventoryBalances/${balanceDocumentId(organizationId, "lot-product", `transit__${organizationId}__lot-branch`, lotB)}`).get()).get("onHandQuantity")).toBe(0);
    await call(manager, "closeTransfer", { transferId, expectedVersion: 1, idempotencyKey: crypto.randomUUID() }); expect((await adminDb.doc(`transfers/${transferId}`).get()).get("status")).toBe("closed");
  }, 90_000);
});
