"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { callAdministration } from "@/features/administration/api";
import { useBillingOperation } from "./use-billing-operation";
interface Account { id: string; code: string; name: string; purpose: string | null }
interface Workspace { mapping: { version: number; deferredService: Account; providerPayable: Account } | null; accounts: Account[] }
export function BillingControls({ ownerKey }: { ownerKey: string }) {
  const [data, setData] = useState<Workspace | null>(null), [service, setService] = useState(""), [provider, setProvider] = useState(""), [reason, setReason] = useState(""), [readError, setError] = useState("");
  const operation = useBillingOperation(`${ownerKey}:controls`);
  useEffect(() => { let current = true; void callAdministration<object, Workspace>("billingControls", { action: "workspace" }).then(result => { if (current) { setData(result); setService(result.mapping?.deferredService.id ?? ""); setProvider(result.mapping?.providerPayable.id ?? ""); } }, cause => { if (current) setError(cause instanceof Error ? cause.message : "Billing controls could not be loaded."); }); return () => { current = false; }; }, []);
  async function save() { try { if (await operation.run("billingControls", { action: "save", deferredServiceAccountId: service, providerPayableAccountId: provider, expectedVersion: data?.mapping?.version ?? 0, reason })) { const result = await callAdministration<object, Workspace>("billingControls", { action: "workspace" }); setData(result); setReason(""); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Saved. Refresh the control workspace to see the latest configuration."); } }
  return <section aria-label="Mixed billing account controls" className="surface space-y-3 p-5"><h2 className="text-lg font-semibold">Mixed billing account controls</h2><p className="text-sm">Choose two reviewed, dedicated liability accounts already created in Company ledger accounts. Account numbers are chosen by your accountant. Services defer unpaid gross charges and release company income and configured VAT only on allocated receipts. Provider funds remain a separate payable; customer advances keep their existing account. Mapping revisions retain prior invoice accounts and permanently protect those controls from manual journals or account edits. An account with prior unrelated postings cannot be repurposed here.</p>{data && <p className="text-sm">{data.mapping ? `Current configuration version ${data.mapping.version}` : "Not configured. Mixed billing cannot post until reviewed accounts are selected."}</p>}<fieldset className="grid gap-3 sm:grid-cols-2" disabled={operation.busy || Boolean(operation.pending)}>{([["Deferred service control", service, setService, "deferred_service"], ["Provider funds payable", provider, setProvider, "provider_payable"]] as const).map(([label, value, setter, purpose]) => <label key={label}>{label}<select className="input block w-full" value={value} onChange={e => setter(e.target.value)}><option value="">Choose reviewed account</option>{data?.accounts.filter(account => !account.purpose || account.purpose === purpose).map(account => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></label>)}<label className="sm:col-span-2">Review reason<textarea className="input block w-full" value={reason} onChange={e => setReason(e.target.value)}/></label></fieldset><Button disabled={!operation.ready || operation.busy || (!operation.pending && (!data || !service || !provider || service === provider || reason.trim().length < 5))} onClick={() => void save()}>{operation.pending ? "Retry saved control configuration" : "Save reviewed account mappings"}</Button>{(readError || operation.error) && <p role="alert" className="text-red-800">{readError || operation.error}</p>}</section>;
}
