"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { callAdministration } from "@/features/administration/api";
import { downloadCsv, formatNaira, nairaToKobo } from "@/features/inventory/format";
import { useBillingOperation } from "./use-billing-operation";
interface Row { saleId: string; saleNumber: string; branchId: string; componentId: string; supplierId: string; supplierName: string; originalMinor: number; creditedMinor: number; collectedMinor: number; settledMinor: number; outstandingMinor: number; invoiceDate: string }
interface Page { rows: Row[]; nextCursorId: string | null; summary: Pick<Row, "originalMinor" | "creditedMinor" | "collectedMinor" | "settledMinor" | "outstandingMinor"> | null; scannedInvoices: number }
interface Payment { id: string; componentId: string; entryType: string; amountMinor: number; recoveredMinor: number; paidAt: string; method: string; reference: string }
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Africa/Lagos", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
export function ProviderFunds({ ownerKey, branchId, accounts, canPay, canRecover }: { ownerKey: string; branchId?: string; accounts: Array<{ id: string; bankName: string; accountName: string }>; canPay: boolean; canRecover: boolean }) {
  return <ProviderFundsRegister key={`${ownerKey}:${branchId ?? "all"}`} {...{ ownerKey, branchId, accounts, canPay, canRecover }} />;
}
function ProviderFundsRegister({ ownerKey, branchId, accounts, canPay, canRecover }: { ownerKey: string; branchId?: string; accounts: Array<{ id: string; bankName: string; accountName: string }>; canPay: boolean; canRecover: boolean }) {
  const [fromDate, setFrom] = useState(() => `${today().slice(0, 7)}-01`), [toDate, setTo] = useState(today), [page, setPage] = useState<Page | null>(null), [cursors, setCursors] = useState<Array<string | undefined>>([undefined]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [selected, setSelected] = useState<Row | null>(null), [history, setHistory] = useState<Payment[]>([]), [action, setAction] = useState<"settle" | "recover">("settle"), [amount, setAmount] = useState(""), [method, setMethod] = useState("cash"), [bank, setBank] = useState(""), [reference, setReference] = useState(""), [reason, setReason] = useState(""), [original, setOriginal] = useState("");
  const operation = useBillingOperation(`${ownerKey}:provider:${branchId ?? "all"}`), locked = busy || operation.busy || Boolean(operation.pending);
  useEffect(() => { let current = true; const timer = window.setTimeout(() => { setPage(null); setSelected(null); setBusy(true); setError(""); void callAdministration<object, Page>("providerFunds", { action: "workspace", branchId, fromDate, toDate, cursorId: cursors.at(-1) }).then(result => { if (current) setPage(result); }, cause => { if (current) setError(cause instanceof Error ? cause.message : "Provider register unavailable."); }).finally(() => { if (current) setBusy(false); }); }, 100); return () => { current = false; window.clearTimeout(timer); }; }, [branchId, fromDate, toDate, cursors]);
  async function detail(row: Row) { setBusy(true); setError(""); try { const result = await callAdministration<object, { rows: Row[]; payments: Payment[] }>("providerFunds", { action: "detail", saleId: row.saleId }); setSelected(result.rows.find(item => item.componentId === row.componentId) ?? null); setHistory(result.payments.filter(item => item.componentId === row.componentId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Provider history unavailable."); } finally { setBusy(false); } }
  async function submit() { try { if (!operation.pending && !selected) return; const ok = await operation.run("providerFunds", { action, saleId: selected?.saleId, componentId: selected?.componentId, amountMinor: operation.pending ? 0 : nairaToKobo(Number(amount)), method, bankAccountId: method === "cash" ? undefined : bank, reference, reason, ...(action === "recover" ? { originalPaymentId: original } : {}) }); if (ok) { setSelected(null); setAmount(""); setReference(""); setReason(""); setCursors([undefined]); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Enter a valid amount."); } }
  async function exportAll() { setBusy(true); setError(""); try { const rows: Row[] = [], seen = new Set<string>(), seenCursors = new Set<string>(); let cursor: string | undefined; do { const result = await callAdministration<object, Page>("providerFunds", { action: "workspace", branchId, fromDate, toDate, cursorId: cursor, includeSummary: false }); for (const row of result.rows) { const id = `${row.saleId}:${row.componentId}`; if (seen.has(id)) throw new Error("Provider data changed during export. Refresh and retry."); seen.add(id); rows.push(row); } if (rows.length > 10000 || (rows.length === 10000 && result.nextCursorId)) throw new Error("Choose a shorter range for more than 10,000 obligations; no partial file was exported."); cursor = result.nextCursorId ?? undefined; if (cursor) { if (seenCursors.has(cursor)) throw new Error("Register paging did not advance. Refresh and retry."); seenCursors.add(cursor); } } while (cursor); if (!rows.length) throw new Error("No provider obligations in this range."); downloadCsv(`provider-funds-${fromDate}-${toDate}.csv`, rows.map(row => ({ basis: "Invoice cohort with current credits, collections and provider settlements", storeScope: branchId ?? "All authorized stores", fromDate, toDate, saleNumber: row.saleNumber, supplier: row.supplierName, supplierId: row.supplierId, originalNaira: row.originalMinor / 100, creditedNaira: row.creditedMinor / 100, customerCollectedNaira: row.collectedMinor / 100, providerSettledNaira: row.settledMinor / 100, providerOutstandingNaira: row.outstandingMinor / 100 }))); } catch (cause) { setError(cause instanceof Error ? cause.message : "Export failed."); } finally { setBusy(false); } }
  return <section aria-label="Provider funds register" className="surface space-y-3 p-5"><h2 className="text-lg font-semibold">Provider funds</h2><p className="text-sm">Provider portions of invoices are liabilities, excluded from company income and operating expenses. Dates select invoices issued in the range; totals reflect current credits, customer collections and provider settlements. Amount owed to the provider is separate from money collected from customers. A page can contain no obligations after scanning invoices; use Next to continue.</p><fieldset className="flex flex-wrap gap-3" disabled={locked}><label>From<input className="input block" type="date" value={fromDate} onChange={e => { setFrom(e.target.value); setCursors([undefined]); }}/></label><label>To<input className="input block" type="date" value={toDate} onChange={e => { setTo(e.target.value); setCursors([undefined]); }}/></label><Button variant="outline" disabled={!page} onClick={() => void exportAll()}>Export full provider CSV</Button></fieldset>{page?.summary && <p className="text-sm">Provider owed: <strong>{formatNaira(page.summary.outstandingMinor)}</strong> · Settled: {formatNaira(page.summary.settledMinor)} · Customer funds allocated: {formatNaira(page.summary.collectedMinor)}</p>}<div className="overflow-x-auto"><table className="min-w-[700px] w-full text-left text-sm"><thead><tr>{["Invoice / provider", "Original", "Credits", "Customer collected", "Provider settled", "Provider owed", "Details"].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{page?.rows.map(row => <tr className="border-t" key={`${row.saleId}:${row.componentId}`}><td className="p-2">{row.saleNumber}<br/>{row.supplierName}</td>{[row.originalMinor, row.creditedMinor, row.collectedMinor, row.settledMinor, row.outstandingMinor].map((value, i) => <td key={i} className="p-2">{formatNaira(value)}</td>)}<td><Button size="sm" variant="outline" disabled={locked} onClick={() => void detail(row)}>History / payment</Button></td></tr>)}</tbody></table></div>{!page?.rows.length && <p className="text-sm">{busy ? "Loading provider obligations…" : "No provider obligations on this scanned page."}</p>}<div className="flex gap-3"><Button variant="outline" disabled={locked || cursors.length < 2} onClick={() => setCursors(cursors.slice(0, -1))}>Previous</Button><Button variant="outline" disabled={locked || !page?.nextCursorId} onClick={() => setCursors([...cursors, page!.nextCursorId!])}>Next</Button></div>
    {selected && <div className="space-y-3 rounded border p-3"><h3 className="font-semibold">{selected.saleNumber} · {selected.supplierName}</h3><p>Provider owed {formatNaira(selected.outstandingMinor)}. Included company service fees remain separate.</p>{history.map(item => <p key={item.id} className="text-sm">{item.entryType}: {formatNaira(item.amountMinor)} · {item.method} · {item.reference} · {new Date(item.paidAt).toLocaleString("en-NG", { timeZone: "Africa/Lagos" })}{item.recoveredMinor ? ` · recovered ${formatNaira(item.recoveredMinor)}` : ""}</p>)}{canPay && <fieldset disabled={locked} className="grid gap-3 sm:grid-cols-2"><label>Action<select className="input block w-full" value={action} onChange={e => setAction(e.target.value as typeof action)}><option value="settle">Pay provider</option>{canRecover && <option value="recover">Record recovered / returned provider funds</option>}</select></label>{action === "recover" && <label>Original provider settlement<select className="input block w-full" value={original} onChange={e => setOriginal(e.target.value)}><option value="">Select settlement</option>{history.filter(item => item.entryType === "settlement" && item.amountMinor > item.recoveredMinor).map(item => <option key={item.id} value={item.id}>{item.reference} · {formatNaira(item.amountMinor - item.recoveredMinor)} recoverable</option>)}</select></label>}<label>Amount (₦)<input className="input block w-full" type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)}/></label><label>Funding / receiving method<select className="input block w-full" value={method} onChange={e => { setMethod(e.target.value); setBank(""); }}><option value="cash">Company cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option></select></label>{method !== "cash" && <label>Company financial account<select className="input block w-full" value={bank} onChange={e => setBank(e.target.value)}><option value="">Select account</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.bankName} · {account.accountName}</option>)}</select></label>}<label>Actual payment / recovery reference<input className="input block w-full" value={reference} onChange={e => setReference(e.target.value)}/></label><label>Reason<input className="input block w-full" value={reason} onChange={e => setReason(e.target.value)}/></label><Button disabled={!operation.ready || !amount || Number(amount) <= 0 || reference.trim().length < 3 || reason.trim().length < 5 || (method !== "cash" && !bank) || (action === "recover" && !original)} onClick={() => void submit()}>{action === "settle" ? "Record provider payment" : "Record actual provider recovery"}</Button></fieldset>}</div>}
    {operation.pending && <div className="rounded border border-amber-300 p-3 text-sm">A provider transaction has saved instructions awaiting a confirmed response. Retry those instructions before recording another payment.<Button className="ml-2" disabled={!operation.ready || operation.busy} onClick={() => void submit()}>Retry saved provider transaction</Button></div>}{(error || operation.error) && <p role="alert" className="text-red-800">{error || operation.error}</p>}
  </section>;
}
