"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Search, UserPlus } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/ui/status-badge";
import { useAuth } from "@/features/auth/auth-context";
import { callAdministration } from "@/features/administration/api";
import { useOrganizationCollection } from "@/features/administration/use-organization-collection";
import { hasPermission } from "@/lib/permissions/roles";
import { roleIds, type Branch, type UserProfile, type Warehouse } from "@/types/domain";

const formSchema = z.object({ email: z.string().email(), displayName: z.string().min(2), phoneNumber: z.string().optional(), employeeReference: z.string().optional(), roleId: z.enum(roleIds), branchIds: z.array(z.string()), warehouseIds: z.array(z.string()), status: z.enum(["active", "inactive", "suspended"]) });
type Values = z.infer<typeof formSchema>;
const defaults: Values = { email: "", displayName: "", phoneNumber: "", employeeReference: "", roleId: "branch_requester", branchIds: [], warehouseIds: [], status: "active" };

export default function UsersPage() {
  const { profile } = useAuth(); const users = useOrganizationCollection<UserProfile>("users"); const branches = useOrganizationCollection<Branch>("branches"); const warehouses = useOrganizationCollection<Warehouse>("warehouses");
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [branchId, setBranchId] = useState(""); const [warehouseId, setWarehouseId] = useState(""); const [editing, setEditing] = useState<UserProfile | null>(null); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState<string | null>(null); const [invitationLink, setInvitationLink] = useState<string | null>(null);
  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(formSchema), defaultValues: defaults });
  const allowed = profile ? hasPermission(profile, "user.manage") : false;
  const filtered = useMemo(() => users.data.filter((user) => (!search || `${user.displayName} ${user.email}`.toLowerCase().includes(search.toLowerCase())) && (!role || user.roleId === role) && (!status || user.status === status) && (!branchId || user.branchIds.includes(branchId)) && (!warehouseId || user.warehouseIds.includes(warehouseId))), [users.data, search, role, status, branchId, warehouseId]);
  function open(user?: UserProfile) { setEditing(user ?? null); setInvitationLink(null); reset(user ? { email: user.email, displayName: user.displayName, phoneNumber: user.phoneNumber ?? "", employeeReference: user.employeeReference ?? "", roleId: user.roleId, branchIds: user.branchIds, warehouseIds: user.warehouseIds, status: user.status } : defaults); setShowForm(true); }
  const submit = handleSubmit(async (values) => {
    setMessage(null);
    try {
      if (editing) await callAdministration("updateOrganizationUser", { ...values, userId: editing.id, email: undefined, reason: "Administrative profile update", idempotencyKey: crypto.randomUUID() });
      else { const result = await callAdministration<Values & { idempotencyKey: string }, { invitationLink: string | null }>("createOrganizationUser", { ...values, idempotencyKey: crypto.randomUUID() }); setInvitationLink(result.invitationLink); setMessage(result.invitationLink ? "User created. Copy the invitation link below and send it through an approved channel." : "User created; configure an email action handler to deliver invitations."); }
      setShowForm(false);
    } catch { setMessage("The secure user operation was rejected. Review assignments and your authority."); }
  });
  if (!allowed) return <div className="rounded-xl border bg-white p-8"><h1 className="text-2xl font-semibold">Users</h1><p className="mt-2 text-sm text-[var(--muted)]">You do not have user-management permission.</p></div>;
  return <div className="space-y-5"><div className="flex items-end justify-between"><div><h1 className="text-3xl font-semibold">Users</h1><p className="text-[var(--muted)]">Provision accounts and control organization assignments.</p></div><Button onClick={() => open()}><UserPlus className="mr-2 size-4"/>Create user</Button></div>
    <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-5"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users" className="w-full rounded-lg border py-2.5 pl-9 pr-3"/></label><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-lg border px-3"><option value="">All roles</option>{roleIds.map((id) => <option key={id} value={id}>{id.replaceAll("_", " ")}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border px-3"><option value="">All statuses</option><option>active</option><option>inactive</option><option>suspended</option></select><select value={branchId} onChange={(event) => setBranchId(event.target.value)} className="rounded-lg border px-3"><option value="">All branches</option>{branches.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)} className="rounded-lg border px-3"><option value="">All warehouses</option>{warehouses.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>
    {message && <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><p>{message}</p>{invitationLink && <div className="mt-2 flex gap-2"><input aria-label="One-time invitation link" readOnly value={invitationLink} className="min-w-0 flex-1 rounded border bg-white px-2 py-1 font-mono text-xs"/><Button type="button" variant="secondary" onClick={() => navigator.clipboard.writeText(invitationLink)}>Copy</Button></div>}</div>}{users.error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{users.error}</p>}
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{["User", "Role", "Branches", "Warehouses", "Status", ""].map((label) => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{users.loading ? <tr><td colSpan={6} className="p-8 text-center">Loading users…</td></tr> : filtered.length === 0 ? <tr><td colSpan={6} className="p-8 text-center text-[var(--muted)]">No users match these filters.</td></tr> : filtered.map((user) => <tr key={user.id} className="border-t"><td className="px-4 py-3"><strong>{user.displayName}</strong><span className="block text-xs text-[var(--muted)]">{user.email}</span></td><td className="px-4">{user.roleId.replaceAll("_", " ")}</td><td className="px-4">{user.branchIds.length}</td><td className="px-4">{user.warehouseIds.length}</td><td className="px-4"><StatusBadge tone={user.status === "active" ? "success" : "warning"}>{user.status}</StatusBadge></td><td className="px-4"><Button variant="ghost" onClick={() => open(user)}>Edit</Button></td></tr>)}</tbody></table></div>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/50 p-4"><form onSubmit={submit} className="my-8 w-full max-w-2xl space-y-4 rounded-2xl bg-white p-6"><div><h2 className="text-xl font-semibold">{editing ? "Edit user" : "Create user"}</h2><p className="text-sm text-[var(--muted)]">Assignments are revalidated by the server.</p></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Email<input {...register("email")} disabled={Boolean(editing)} className="mt-1 w-full rounded-lg border p-2.5"/>{errors.email && <span className="text-xs text-red-700">Valid email required</span>}</label><label className="text-sm">Display name<input {...register("displayName")} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="text-sm">Phone<input {...register("phoneNumber")} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="text-sm">Employee reference<input {...register("employeeReference")} className="mt-1 w-full rounded-lg border p-2.5"/></label><label className="text-sm">Role<select {...register("roleId")} className="mt-1 w-full rounded-lg border p-2.5">{roleIds.map((id) => <option key={id} value={id}>{id.replaceAll("_", " ")}</option>)}</select></label><label className="text-sm">Status<select {...register("status")} className="mt-1 w-full rounded-lg border p-2.5"><option>active</option><option>inactive</option><option>suspended</option></select></label><label className="text-sm">Branches<select multiple {...register("branchIds")} className="mt-1 h-28 w-full rounded-lg border p-2.5">{branches.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm">Warehouses<select multiple {...register("warehouseIds")} className="mt-1 h-28 w-full rounded-lg border p-2.5">{warehouses.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Cancel</Button><Button disabled={isSubmitting}>{isSubmitting ? "Saving…" : "Save securely"}</Button></div></form></div>}
  </div>;
}
