"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { callAdministration } from "@/features/administration/api";
import { formatNaira, nairaToKobo } from "@/features/inventory/format";
import type { PosCartLine, PosWorkspace, ServiceCaseCharge } from "./types";
export function ServiceLineOptions({ line, workspace, customerId, online, onChange }: { line: PosCartLine; workspace: PosWorkspace; customerId: string; online: boolean; onChange: (line: PosCartLine) => void }) {
  const [partId, setPart] = useState(""), [providerId, setProvider] = useState(line.providerFunds?.supplierId ?? ""), [providerAmount, setAmount] = useState(line.providerFunds ? String(line.providerFunds.amountMinor / 100) : ""), [caseId, setCase] = useState(line.serviceCase?.id ?? ""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [providers, setProviders] = useState(workspace.providers ?? []), [providerCursor, setProviderCursor] = useState(workspace.providerNextCursorId);
  async function moreProviders() { setBusy(true); setError(""); try { const page = await callAdministration<object, { providers: NonNullable<PosWorkspace["providers"]>; nextCursorId: string | null }>("getServiceBillingCase", { action: "providers", cursorId: providerCursor }); setProviders(current => [...new Map([...current, ...page.providers].map(item => [item.id, item])).values()]); setProviderCursor(page.nextCursorId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Providers could not be loaded."); } finally { setBusy(false); } }
  async function linkCase() {
    setBusy(true); setError("");
    try { const serviceCase = await callAdministration<object, ServiceCaseCharge>("getServiceBillingCase", { caseId: caseId.trim(), branchId: workspace.branch.id, serviceItemId: line.product.id, customerId: customerId || undefined }); onChange({ ...line, quantity: 1, priceTier: "retail", sellingPriceMinor: undefined, priceOverrideReason: undefined, serviceCase, caseVerified: true }); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Case could not be linked."); }
    finally { setBusy(false); }
  }
  return <details className="mt-3 rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-semibold">Service billing details</summary><div className="mt-3 space-y-3 text-sm">
    <p>Separately charged parts go in the main basket as goods. Parts included below are consumed once when payment is confirmed, including when charged goods are reserved for later. Their cost is included in this service; a service credit does not restock them.</p>
    <fieldset disabled={!online || busy} className="space-y-3">
      <label className="block">Physical part included in fee<select className="input block w-full" value={partId} onChange={e => setPart(e.target.value)}><option value="">Select existing goods</option>{workspace.products.filter(p => p.itemKind !== "service" && !line.includedParts?.some(part => part.productId === p.id)).map(p => <option key={p.id} value={p.id}>{p.name} · {p.sku} · {p.availableQuantity} available</option>)}</select></label>
      <Button size="sm" variant="outline" disabled={!partId || (line.includedParts?.length ?? 0) >= 10} onClick={() => { onChange({ ...line, includedParts: [...line.includedParts ?? [], { productId: partId, quantity: 1 }] }); setPart(""); }}>Include part in service fee</Button>
      {line.includedParts?.map(part => { const product = workspace.products.find(p => p.id === part.productId); return <div key={part.productId} className="space-y-2 rounded border bg-white p-2"><strong>{product?.name ?? "Unavailable part"}</strong><label className="block">Included quantity<input className="input ml-2 w-24" type="number" min="1" max="100000" value={part.quantity} onChange={e => { const quantity = Number(e.target.value); if (Number.isSafeInteger(quantity) && quantity > 0 && quantity <= 100000) onChange({ ...line, includedParts: line.includedParts!.map(p => p.productId === part.productId ? { ...p, quantity } : p) }); }}/></label>{product?.trackingType === "serial" && <label className="block">Included part serials<textarea className="input block w-full" value={part.serialNumbers?.join("\n") ?? ""} onChange={e => onChange({ ...line, includedParts: line.includedParts!.map(p => p.productId === part.productId ? { ...p, serialNumbers: e.target.value.split(/\r?\n/).map(s => s.trim()).filter(Boolean) } : p) })}/></label>}<Button size="sm" variant="ghost" onClick={() => onChange({ ...line, includedParts: line.includedParts!.filter(p => p.productId !== part.productId).length ? line.includedParts!.filter(p => p.productId !== part.productId) : undefined })}>Remove included part</Button></div>; })}
      <label className="block">Delivery/service provider<select className="input block w-full" value={providerId} onChange={e => setProvider(e.target.value)}><option value="">Select existing supplier</option>{providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name} · {provider.supplierType}</option>)}</select></label>
      {providerCursor && <Button size="sm" variant="outline" onClick={() => void moreProviders()}>Load more existing suppliers</Button>}
      <label className="block">Provider funds (₦), separate from company fee<input className="input block w-full" type="number" min="0.01" step="0.01" value={providerAmount} onChange={e => setAmount(e.target.value)}/></label>
      <Button size="sm" variant="outline" disabled={!providerId || !providerAmount} onClick={() => { try { const amountMinor = nairaToKobo(Number(providerAmount)); if (!amountMinor) throw new Error("Enter positive provider funds."); onChange({ ...line, providerFunds: { supplierId: providerId, amountMinor } }); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Invalid amount."); } }}>Apply provider funds</Button>
      {line.providerFunds && <p>Recorded provider funds: {formatNaira(line.providerFunds.amountMinor)}. This is a payable, excluded from company income. <Button size="sm" variant="ghost" onClick={() => { onChange({ ...line, providerFunds: undefined }); setProvider(""); setAmount(""); }}>Remove provider funds</Button></p>}
      <label className="block">Optional confirmed aftersales case ID<input className="input block w-full" value={caseId} onChange={e => setCase(e.target.value)}/></label><Button size="sm" variant="outline" disabled={!caseId.trim()} onClick={() => void linkCase()}>Link / refresh confirmed case</Button>
      {line.serviceCase && <p>Case {line.serviceCase.caseNumber}: fixed charge {formatNaira(line.serviceCase.grossMinor)}, already received {formatNaira(line.serviceCase.paidMinor)}. {line.caseVerified ? "Prior receipts are carried without new cash or income." : "Refresh this case before checkout."}<Button size="sm" variant="ghost" onClick={() => onChange({ ...line, serviceCase: undefined, caseVerified: undefined })}>Unlink case; use new catalogue charge</Button></p>}
    </fieldset>{!online && <p>Services require internet access.</p>}{error && <p role="alert" className="text-red-800">{error}</p>}
  </div></details>;
}
